application: realtime-inspector
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /css
  static_dir: css
  secure: always

- url: /components
  static_dir: components
  secure: always

- url: /vendor
  static_dir: vendor
  secure: always

- url: /
  static_files: templates/index.html
  upload: templates/index.html
  secure: always

skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Build files that have no effect in App Engine's runtime.
- ^.*\.MF$
- ^.*\.CMF$
- ^.*\.so$
- ^.*pywrap.+\.py$
- ^.*\.jslib$